In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
# going through each csv file and creating a corresponding dataframe
df_gender = pd.read_csv("data/reddit_comments_gender_female_processed_phrase_annotated.csv")
df_gender

,attribute_in_window,comment,phrase,bias_sent,bias_phrase,Unnamed: 5
0,True,im sorry this is happening for you. at least y...,least you know whats happening now. narcissist...,0,0,NaN
1,True,their mothers are in on the joke art project,their mothers are in on the joke art project,1,1,NaN
2,True,i feel like this is some deep artistic dance t...,artistic dance thats trying to highlight how m...,0,0,NaN
3,True,or biology. over protective and smothering mot...,or biology. over protective and smothering mot...,0,0,NaN
4,True,writing poetry to a girl is the fastest way to...,writing poetry to a girl is the fastest way to...,0,0,NaN
...,...,...,...,...,...,...
2995,True,clean your fucking bathroom you beta-maid piec...,bathroom you beta-maid piece of shit your girl...,0,0,NaN
2996,True,they fucked with the dubs of dragon maid and m...,the dubs of dragon maid and my girlfriend is a...,0,0,NaN
2997,True,its cause im at minute maid but my girlfriend ...,cause im at minute maid but my girlfriend is a...,0,0,NaN
2998,True,my profile. im a ft deli clerk and pay range i...,and pay range is listed as to. girlfriend is p...,1,1,NaN
2999,True,clerk trainer been here for.5 years. my girlfr...,clerk trainer been here for.5 years. my girlfr...,0,0,NaN

In [3]:
df_orientation = pd.read_csv("data/reddit_comments_orientation_lgbtq_processed_phrase_annotated.csv")
df_orientation

,id,attribute_in_window,comment,phrase,bias_sent,bias_phrase
0,NaN,True,would it turn you on if i said that all gays a...,you on if i said that all gays are mentally il...,0.0,0.0
1,NaN,True,yeah except gay people are mentally ill,yeah except gay people are mentally ill,1.0,1.0
2,NaN,True,gay people are mentally ill,gay people are mentally ill,1.0,1.0
3,NaN,True,wow gay people truly are mentally ill after al...,wow gay people truly are mentally ill after all,1.0,1.0
4,NaN,True,thats like saying gay people are mentally ill ...,thats like saying gay people are mentally ill ...,NaN,NaN
...,...,...,...,...,...,...
7988,NaN,True,pansexuals are pretty weird,pansexuals are pretty weird,1.0,1.0
7989,NaN,True,d ud e pansexuals are fucking weird,d ud e pansexuals are fucking weird,1.0,1.0
7990,NaN,True,why is there this weird exclusionary thing wit...,with poc and the lgbtq community? because quee...,NaN,NaN
7991,NaN,True,pansexuals are just weird to me. its as though...,pansexuals are just weird to me. its as,NaN,1.0
7992,NaN,True,many queer people are homeless or are in insec...,many queer people are homeless or are in insecure,0.0,0.0

In [4]:
df_race = pd.read_csv("data/reddit_comments_race_black_processed_phrase_annotated.csv")
df_race

,id,attribute_in_window,comment,phrase,bias_sent,bias_phrase
0,fxlkyso,True,so what does this video try to prove that mexi...,video try to prove that mexicans and african a...,0.0,0.0
1,fxdm2pg,True,the statistic is about violent crimes or murde...,violent crimes or murders both of which black ...,1.0,1.0
2,fxek9n6,True,yep its totally because of melanine! that shit...,that shit causes so much violence! because bla...,0.0,1.0
3,fv14wca,True,we are blaming the africans because the africa...,we are blaming the africans because the africa...,1.0,1.0
4,fv37xgq,True,why .3? we agree that africans are violent and...,why .3? we agree that africans are violent and...,1.0,1.0
...,...,...,...,...,...,...
2995,dzp2h1c,True,as loud as black girls are neither can they.,as loud as black girls are neither can they.,NaN,NaN
2996,dn0ezw7,True,black girls are loud. i have an obnoxious laug...,black girls are loud. i have an obnoxious,1.0,1.0
2997,dhfi80p,True,many black girls are loud.,many black girls are loud.,1.0,1.0
2998,dqhoa7l,True,white cops shouldnt have to raise black kids t...,white cops shouldnt have to raise black kids t...,1.0,1.0
2999,f0vu3ny,True,i see that you are implying that the dark-skin...,see that you are implying that the dark-skinne...,NaN,NaN

In [5]:
df_religion2 = pd.read_csv("data/reddit_comments_religion2_muslims_processed_phrase_annotated.csv")
df_religion2

,id,attribute_in_window,comment,phrase,bias_sent,bias_phrase
0,fxqotw4,True,its like the muslim people are terrorist or je...,its like the muslim people are terrorist or je...,0.0,1.0
1,fy1nhu8,False,muslim people are so kind. i should become a t...,muslim people are so kind. i should become,0.0,0.0
2,fxqrpjr,True,now i know why the stereotype of all muslims a...,why the stereotype of all muslims and arabs ar...,1.0,0.0
3,fyqyg0s,True,not all arabs are terrorists but all terrorist...,not all arabs are terrorists but all terrorist...,1.0,1.0
4,fzb1uxf,True,so youre just a racist that thinks all arabs a...,youre just a racist that thinks all arabs are ...,0.0,0.0
...,...,...,...,...,...,...
10579,dlre79o,True,false comparison not every muslim is violent. ...,false comparison not every muslim is violent. ...,NaN,NaN
10580,dlreadd,True,if every nazi is violent because they believe ...,believe in a violent ideology then every musli...,NaN,NaN
10581,dlreflm,True,guys i dont think they know just how stupid th...,how stupid they are not every muslim is viole...,NaN,NaN
10582,disuk3y,True,not every muslim is violent not every german i...,not every muslim is violent not every german i...,NaN,NaN
10583,dj3vd8k,True,i never said every muslim is violent thats abs...,i never said every muslim is violent thats abs...,0.0,0.0

In [6]:
df_religion1 = pd.read_csv("data/reddit_comments_religion1_jews_processed_phrase_annotated.csv", encoding='latin-1')
df_religion1

,id,attribute_in_window,comment,phrase,bias_sent,bias_phrase
0,fxqotw4,True,its like the muslim people are terrorist or je...,like the muslim people are terrorist or jewish...,0,1.0
1,fz9lk7t,True,jewish people owning everything is an antisemi...,antisemitic trope that ties in with the belief...,0,0.0
2,fxgj0wi,True,if i had said many jews are greedy youd have f...,if i had said many jews are greedy youd have f...,0,0.0
3,fxo34py,True,just like come on jews you shouldnt be upset o...,just like come on jews you shouldnt be upset o...,0,1.0
4,fxwu189,True,based on the stereotype that jews are greedy. ...,based on the stereotype that jews are greedy. ...,0,0.0
...,...,...,...,...,...,...
3549,dx3bw4p,False,circumcision has to take place on theth day af...,theth day after birth. thats not true judaism ...,0,0.0
3550,du7ubbm,False,they can indeed but denying your child circumc...,him jewishness and gods love. not many jewish ...,1,0.0
3551,dkyeubx,True,and he can look up brit shalom.this is a legit...,look up brit shalom.this is a legitimate jewis...,0,0.0
3552,dyo2vy1,True,your jewish parents are pretty frugal with the...,your jewish parents are pretty frugal with the...,1,1.0
3553,fabxomo,True,apparently im a emasculated manlet who will ne...,the joy of uncircumcised sex because my jewish...,1,1.0

In [7]:
df_gender.head()

,attribute_in_window,comment,phrase,bias_sent,bias_phrase,Unnamed: 5
0,True,im sorry this is happening for you. at least y...,least you know whats happening now. narcissist...,0,0,NaN
1,True,their mothers are in on the joke art project,their mothers are in on the joke art project,1,1,NaN
2,True,i feel like this is some deep artistic dance t...,artistic dance thats trying to highlight how m...,0,0,NaN
3,True,or biology. over protective and smothering mot...,or biology. over protective and smothering mot...,0,0,NaN
4,True,writing poetry to a girl is the fastest way to...,writing poetry to a girl is the fastest way to...,0,0,NaN

In [8]:
df_gender['bias_phrase'] # this is the label

0       0
1       1
2       0
3       0
4       0
       ..
2995    0
2996    0
2997    0
2998    1
2999    0
Name: bias_phrase, Length: 3000, dtype: int64

In [9]:
# taking care of missing values
nan_detected = np.sum(df_gender.isnull(), axis=0)
nan_detected

attribute_in_window       0
comment                   0
phrase                    0
bias_sent                 0
bias_phrase               0
Unnamed: 5             2999
dtype: int64

In [10]:
# should we drop or find the average
# given that they are unamed, we can just drop
missing_columns = df_gender.columns[df_gender.isnull().any()].tolist()

In [11]:
missing_columns

['Unnamed: 5']

In [12]:
df_gender = df_gender.drop(columns = missing_columns, axis = 0)

In [13]:
df_gender

,attribute_in_window,comment,phrase,bias_sent,bias_phrase
0,True,im sorry this is happening for you. at least y...,least you know whats happening now. narcissist...,0,0
1,True,their mothers are in on the joke art project,their mothers are in on the joke art project,1,1
2,True,i feel like this is some deep artistic dance t...,artistic dance thats trying to highlight how m...,0,0
3,True,or biology. over protective and smothering mot...,or biology. over protective and smothering mot...,0,0
4,True,writing poetry to a girl is the fastest way to...,writing poetry to a girl is the fastest way to...,0,0
...,...,...,...,...,...
2995,True,clean your fucking bathroom you beta-maid piec...,bathroom you beta-maid piece of shit your girl...,0,0
2996,True,they fucked with the dubs of dragon maid and m...,the dubs of dragon maid and my girlfriend is a...,0,0
2997,True,its cause im at minute maid but my girlfriend ...,cause im at minute maid but my girlfriend is a...,0,0
2998,True,my profile. im a ft deli clerk and pay range i...,and pay range is listed as to. girlfriend is p...,1,1
2999,True,clerk trainer been here for.5 years. my girlfr...,clerk trainer been here for.5 years. my girlfr...,0,0

In [14]:
# now doing the same for all the rest of the dataframes
df_orientation.head()
nan_detected = np.sum(df_orientation.isnull(), axis=0)
nan_detected

id                     7993
attribute_in_window       0
comment                   0
phrase                    0
bias_sent              6010
bias_phrase            5975
dtype: int64

In [15]:
df_orientation

,id,attribute_in_window,comment,phrase,bias_sent,bias_phrase
0,NaN,True,would it turn you on if i said that all gays a...,you on if i said that all gays are mentally il...,0.0,0.0
1,NaN,True,yeah except gay people are mentally ill,yeah except gay people are mentally ill,1.0,1.0
2,NaN,True,gay people are mentally ill,gay people are mentally ill,1.0,1.0
3,NaN,True,wow gay people truly are mentally ill after al...,wow gay people truly are mentally ill after all,1.0,1.0
4,NaN,True,thats like saying gay people are mentally ill ...,thats like saying gay people are mentally ill ...,NaN,NaN
...,...,...,...,...,...,...
7988,NaN,True,pansexuals are pretty weird,pansexuals are pretty weird,1.0,1.0
7989,NaN,True,d ud e pansexuals are fucking weird,d ud e pansexuals are fucking weird,1.0,1.0
7990,NaN,True,why is there this weird exclusionary thing wit...,with poc and the lgbtq community? because quee...,NaN,NaN
7991,NaN,True,pansexuals are just weird to me. its as though...,pansexuals are just weird to me. its as,NaN,1.0
7992,NaN,True,many queer people are homeless or are in insec...,many queer people are homeless or are in insecure,0.0,0.0

In [16]:
# now because the id section is just NaNs we can drop that too? (Unless the id is important in some way to the data frame)
df_orientation = df_orientation.drop(columns = ["id"], axis = 0)

In [17]:
df_orientation.head()

,attribute_in_window,comment,phrase,bias_sent,bias_phrase
0,True,would it turn you on if i said that all gays a...,you on if i said that all gays are mentally il...,0.0,0.0
1,True,yeah except gay people are mentally ill,yeah except gay people are mentally ill,1.0,1.0
2,True,gay people are mentally ill,gay people are mentally ill,1.0,1.0
3,True,wow gay people truly are mentally ill after al...,wow gay people truly are mentally ill after all,1.0,1.0
4,True,thats like saying gay people are mentally ill ...,thats like saying gay people are mentally ill ...,NaN,NaN

In [18]:
# dropping the rows with missing values from bias sent and bias phrase too (even if it means we'll have less data for these sections)
df_orientation = df_orientation.dropna()

In [19]:
df_orientation # the size decreased

,attribute_in_window,comment,phrase,bias_sent,bias_phrase
0,True,would it turn you on if i said that all gays a...,you on if i said that all gays are mentally il...,0.0,0.0
1,True,yeah except gay people are mentally ill,yeah except gay people are mentally ill,1.0,1.0
2,True,gay people are mentally ill,gay people are mentally ill,1.0,1.0
3,True,wow gay people truly are mentally ill after al...,wow gay people truly are mentally ill after all,1.0,1.0
5,True,same here. she told me today that gay people a...,me today that gay people are only gay because ...,0.0,1.0
...,...,...,...,...,...
7986,True,well queer people are strange.,well queer people are strange.,1.0,1.0
7987,True,pansexuals are starting to have some really we...,pansexuals are starting to have some really weird,1.0,1.0
7988,True,pansexuals are pretty weird,pansexuals are pretty weird,1.0,1.0
7989,True,d ud e pansexuals are fucking weird,d ud e pansexuals are fucking weird,1.0,1.0
7992,True,many queer people are homeless or are in insec...,many queer people are homeless or are in insecure,0.0,0.0

In [20]:
# now race
df_race.head()

,id,attribute_in_window,comment,phrase,bias_sent,bias_phrase
0,fxlkyso,True,so what does this video try to prove that mexi...,video try to prove that mexicans and african a...,0.0,0.0
1,fxdm2pg,True,the statistic is about violent crimes or murde...,violent crimes or murders both of which black ...,1.0,1.0
2,fxek9n6,True,yep its totally because of melanine! that shit...,that shit causes so much violence! because bla...,0.0,1.0
3,fv14wca,True,we are blaming the africans because the africa...,we are blaming the africans because the africa...,1.0,1.0
4,fv37xgq,True,why .3? we agree that africans are violent and...,why .3? we agree that africans are violent and...,1.0,1.0

In [21]:
nan_detected_race = np.sum(df_race.isnull(), axis=0)
nan_detected_race

id                       0
attribute_in_window      0
comment                  0
phrase                   0
bias_sent              380
bias_phrase            380
dtype: int64

In [22]:
# replacing missing values in bias_sent and bias_phrase like previously
df_race = df_race.dropna()

In [23]:
nan_detected_race = np.sum(df_race.isnull(), axis=0)
nan_detected_race

id                     0
attribute_in_window    0
comment                0
phrase                 0
bias_sent              0
bias_phrase            0
dtype: int64

In [25]:
df_race = df_race.drop(columns = ["id"], axis = 0)

In [26]:
# to maintain uniformity, got rid of the ID column (each dataframe should have 5 columns)
df_race

,attribute_in_window,comment,phrase,bias_sent,bias_phrase
0,True,so what does this video try to prove that mexi...,video try to prove that mexicans and african a...,0.0,0.0
1,True,the statistic is about violent crimes or murde...,violent crimes or murders both of which black ...,1.0,1.0
2,True,yep its totally because of melanine! that shit...,that shit causes so much violence! because bla...,0.0,1.0
3,True,we are blaming the africans because the africa...,we are blaming the africans because the africa...,1.0,1.0
4,True,why .3? we agree that africans are violent and...,why .3? we agree that africans are violent and...,1.0,1.0
...,...,...,...,...,...
2993,True,it perpetuates the stereotype that all black g...,it perpetuates the stereotype that all black g...,0.0,0.0
2994,True,not all black girls are loud and not all black...,not all black girls are loud and not all black,0.0,0.0
2996,True,black girls are loud. i have an obnoxious laug...,black girls are loud. i have an obnoxious,1.0,1.0
2997,True,many black girls are loud.,many black girls are loud.,1.0,1.0
2998,True,white cops shouldnt have to raise black kids t...,white cops shouldnt have to raise black kids t...,1.0,1.0

In [27]:
# now lastly religion2
df_religion2

,id,attribute_in_window,comment,phrase,bias_sent,bias_phrase
0,fxqotw4,True,its like the muslim people are terrorist or je...,its like the muslim people are terrorist or je...,0.0,1.0
1,fy1nhu8,False,muslim people are so kind. i should become a t...,muslim people are so kind. i should become,0.0,0.0
2,fxqrpjr,True,now i know why the stereotype of all muslims a...,why the stereotype of all muslims and arabs ar...,1.0,0.0
3,fyqyg0s,True,not all arabs are terrorists but all terrorist...,not all arabs are terrorists but all terrorist...,1.0,1.0
4,fzb1uxf,True,so youre just a racist that thinks all arabs a...,youre just a racist that thinks all arabs are ...,0.0,0.0
...,...,...,...,...,...,...
10579,dlre79o,True,false comparison not every muslim is violent. ...,false comparison not every muslim is violent. ...,NaN,NaN
10580,dlreadd,True,if every nazi is violent because they believe ...,believe in a violent ideology then every musli...,NaN,NaN
10581,dlreflm,True,guys i dont think they know just how stupid th...,how stupid they are not every muslim is viole...,NaN,NaN
10582,disuk3y,True,not every muslim is violent not every german i...,not every muslim is violent not every german i...,NaN,NaN
10583,dj3vd8k,True,i never said every muslim is violent thats abs...,i never said every muslim is violent thats abs...,0.0,0.0

In [28]:
nan_detected_religion = np.sum(df_religion2.isnull(), axis=0)
nan_detected_religion

id                        0
attribute_in_window       0
comment                   0
phrase                    1
bias_sent              8782
bias_phrase            8783
dtype: int64

In [29]:
# this seems to be a much larger datset
df_religion2 = df_religion2.dropna()
df_religion2 = df_religion2.drop(columns = ["id"], axis = 0)

In [30]:
df_religion2

,attribute_in_window,comment,phrase,bias_sent,bias_phrase
0,True,its like the muslim people are terrorist or je...,its like the muslim people are terrorist or je...,0.0,1.0
1,False,muslim people are so kind. i should become a t...,muslim people are so kind. i should become,0.0,0.0
2,True,now i know why the stereotype of all muslims a...,why the stereotype of all muslims and arabs ar...,1.0,0.0
3,True,not all arabs are terrorists but all terrorist...,not all arabs are terrorists but all terrorist...,1.0,1.0
4,True,so youre just a racist that thinks all arabs a...,youre just a racist that thinks all arabs are ...,0.0,0.0
...,...,...,...,...,...
10563,True,saying that a muslim is violent because they d...,saying that a muslim is violent because they d...,0.0,1.0
10565,True,funny that a muslim is talking about other rel...,funny that a muslim is talking about other rel...,1.0,1.0
10568,True,a good muslim is a violent racist homophobic ...,a good muslim is a violent racist homophobic one,1.0,1.0
10575,True,yeah no muslim is violent,yeah no muslim is violent,0.0,0.0
10583,True,i never said every muslim is violent thats abs...,i never said every muslim is violent thats abs...,0.0,0.0

In [31]:
# now religion1
df_religion1

,id,attribute_in_window,comment,phrase,bias_sent,bias_phrase
0,fxqotw4,True,its like the muslim people are terrorist or je...,like the muslim people are terrorist or jewish...,0,1.0
1,fz9lk7t,True,jewish people owning everything is an antisemi...,antisemitic trope that ties in with the belief...,0,0.0
2,fxgj0wi,True,if i had said many jews are greedy youd have f...,if i had said many jews are greedy youd have f...,0,0.0
3,fxo34py,True,just like come on jews you shouldnt be upset o...,just like come on jews you shouldnt be upset o...,0,1.0
4,fxwu189,True,based on the stereotype that jews are greedy. ...,based on the stereotype that jews are greedy. ...,0,0.0
...,...,...,...,...,...,...
3549,dx3bw4p,False,circumcision has to take place on theth day af...,theth day after birth. thats not true judaism ...,0,0.0
3550,du7ubbm,False,they can indeed but denying your child circumc...,him jewishness and gods love. not many jewish ...,1,0.0
3551,dkyeubx,True,and he can look up brit shalom.this is a legit...,look up brit shalom.this is a legitimate jewis...,0,0.0
3552,dyo2vy1,True,your jewish parents are pretty frugal with the...,your jewish parents are pretty frugal with the...,1,1.0
3553,fabxomo,True,apparently im a emasculated manlet who will ne...,the joy of uncircumcised sex because my jewish...,1,1.0

In [32]:
nan_detected_religion1 = np.sum(df_religion1.isnull(), axis=0)
nan_detected_religion1

id                        0
attribute_in_window       0
comment                   0
phrase                  185
bias_sent              1420
bias_phrase            1564
dtype: int64

In [33]:
df_religion1 = df_religion1.dropna()
df_religion1 = df_religion1.drop(columns = ["id"], axis = 0)

In [34]:
df_religion1

,attribute_in_window,comment,phrase,bias_sent,bias_phrase
0,True,its like the muslim people are terrorist or je...,like the muslim people are terrorist or jewish...,0,1.0
1,True,jewish people owning everything is an antisemi...,antisemitic trope that ties in with the belief...,0,0.0
2,True,if i had said many jews are greedy youd have f...,if i had said many jews are greedy youd have f...,0,0.0
3,True,just like come on jews you shouldnt be upset o...,just like come on jews you shouldnt be upset o...,0,1.0
4,True,based on the stereotype that jews are greedy. ...,based on the stereotype that jews are greedy. ...,0,0.0
...,...,...,...,...,...
3549,False,circumcision has to take place on theth day af...,theth day after birth. thats not true judaism ...,0,0.0
3550,False,they can indeed but denying your child circumc...,him jewishness and gods love. not many jewish ...,1,0.0
3551,True,and he can look up brit shalom.this is a legit...,look up brit shalom.this is a legitimate jewis...,0,0.0
3552,True,your jewish parents are pretty frugal with the...,your jewish parents are pretty frugal with the...,1,1.0
3553,True,apparently im a emasculated manlet who will ne...,the joy of uncircumcised sex because my jewish...,1,1.0

In [35]:
# now to merge all these dataframes into one dataframe
# but before, let's add another column containing the type of bias
df_gender['bias_type'] = 'gender'
df_gender

,attribute_in_window,comment,phrase,bias_sent,bias_phrase,bias_type
0,True,im sorry this is happening for you. at least y...,least you know whats happening now. narcissist...,0,0,gender
1,True,their mothers are in on the joke art project,their mothers are in on the joke art project,1,1,gender
2,True,i feel like this is some deep artistic dance t...,artistic dance thats trying to highlight how m...,0,0,gender
3,True,or biology. over protective and smothering mot...,or biology. over protective and smothering mot...,0,0,gender
4,True,writing poetry to a girl is the fastest way to...,writing poetry to a girl is the fastest way to...,0,0,gender
...,...,...,...,...,...,...
2995,True,clean your fucking bathroom you beta-maid piec...,bathroom you beta-maid piece of shit your girl...,0,0,gender
2996,True,they fucked with the dubs of dragon maid and m...,the dubs of dragon maid and my girlfriend is a...,0,0,gender
2997,True,its cause im at minute maid but my girlfriend ...,cause im at minute maid but my girlfriend is a...,0,0,gender
2998,True,my profile. im a ft deli clerk and pay range i...,and pay range is listed as to. girlfriend is p...,1,1,gender
2999,True,clerk trainer been here for.5 years. my girlfr...,clerk trainer been here for.5 years. my girlfr...,0,0,gender

In [36]:
# now let's do the same for the rest
df_orientation['bias_type'] = 'orientation'
df_race['bias_type'] = 'race'
df_religion1['bias_type'] = 'religion'
df_religion2['bias_type'] = 'religion'

In [37]:
# now lets combine
df = pd.concat([df_gender,df_orientation,df_race,df_religion1,df_religion2], axis = 0)

In [38]:
df # the whole dataframe containing all the individual bias types

,attribute_in_window,comment,phrase,bias_sent,bias_phrase,bias_type
0,True,im sorry this is happening for you. at least y...,least you know whats happening now. narcissist...,0,0.0,gender
1,True,their mothers are in on the joke art project,their mothers are in on the joke art project,1,1.0,gender
2,True,i feel like this is some deep artistic dance t...,artistic dance thats trying to highlight how m...,0,0.0,gender
3,True,or biology. over protective and smothering mot...,or biology. over protective and smothering mot...,0,0.0,gender
4,True,writing poetry to a girl is the fastest way to...,writing poetry to a girl is the fastest way to...,0,0.0,gender
...,...,...,...,...,...,...
10563,True,saying that a muslim is violent because they d...,saying that a muslim is violent because they d...,0.0,1.0,religion
10565,True,funny that a muslim is talking about other rel...,funny that a muslim is talking about other rel...,1.0,1.0,religion
10568,True,a good muslim is a violent racist homophobic ...,a good muslim is a violent racist homophobic one,1.0,1.0,religion
10575,True,yeah no muslim is violent,yeah no muslim is violent,0.0,0.0,religion
10583,True,i never said every muslim is violent thats abs...,i never said every muslim is violent thats abs...,0.0,0.0,religion

In [39]:
# splitting into testing and training sets
y = df['bias_phrase']
X = df.drop(columns = 'bias_phrase', axis = 1)

In [40]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30,random_state=1234)

In [ ]:
# That's as far as we have gotten